title:            Li Yang
url:              http://aircapsule.com
permalink:        /posts/:year/:month/:day/:title.html
pygments:         true
markdown:         kramdown
rdiscount:
  extensions:     [smart]
google_analytics: UA-21332781-7
timezone:         Europe/London
paginate:         5
links:
  - name:         About
    url:          /about

root: /

# Disqus Comments
disqus_short_name: aircapsule
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-38976134-1

# exclude these file when publish to _site
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']